/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cmcc_jeff_pwdmanager_Utils_RSAUtil */

#ifndef _Included_com_cmcc_jeff_pwdmanager_Utils_RSAUtil
#define _Included_com_cmcc_jeff_pwdmanager_Utils_RSAUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cmcc_jeff_pwdmanager_Utils_RSAUtil
 * Method:    getPrivateKeyFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cmcc_jeff_pwdmanager_Utils_RSAUtil_getPrivateKeyFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
